---


- name: Install the latest version of rsync and cron
  apt:
    name:
      - rsync
      - cron
    state: latest

- name: make sure crond is enabled and started
  ansible.builtin.service:
    name: cron
    state: started
    enabled: yes