---



- name: Install the latest version of rsync and cronie
  dnf:
    name:
      - rsync
      - cronie
    state: latest

- name: make sure crond is enabled and started
  ansible.builtin.service:
    name: crond
    state: started
    enabled: yes